apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  labels:
    app: cpu-stress
spec:
  containers:
  - name: stress
    image: vish/stress
    args:
    - --cpus
    - "2"
    resources:
      requests:
        cpu: "500m"
      limits:
        cpu: "1000m"
